In [2]:
#1 créer une matrice de 3 lignes et 3 colonnes qui contient les valeurs (1,5,8,6,7,3,4,6,2).

import numpy as np
s = np.array([[1,5,8],[6,7,3],[4,6,2]])
print(s)

[[1 5 8]
 [6 7 3]
 [4 6 2]]


In [4]:
#2 créer une matrice de 3 lignes et 4 colonnes remplie de 0.

import numpy as np
s = np.zeros((3,4))
print(s)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
#3 créer une matrice de 3 lignes et 4 colonnes remplie de 1.

import numpy as np
s = np.ones((3,4))
print(s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
#4 créer une matrice de 3 lignes et 4 colonnes remplie de 5.2.

import numpy as np

s = np.full((3,4),5.2)
print(s)

[[5.2 5.2 5.2 5.2]
 [5.2 5.2 5.2 5.2]
 [5.2 5.2 5.2 5.2]]


In [12]:
#5 créer une matrice identitatire de 3 lignes et 3 colonnes.

import numpy as np
s = np.identity((3))
print(s)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
#6 créer une matrice de 3 lignes et 4 colonnes remplie de 5.2.

import numpy as np

s = np.full((3,4),5.2)
print(s)

[[5.2 5.2 5.2 5.2]
 [5.2 5.2 5.2 5.2]
 [5.2 5.2 5.2 5.2]]


In [25]:
#7,8,9,10 créer un tableau à une dimension remplie de 10 valeurs aléatoires comprises entre 0 et 9.

import numpy as np
s = np.random.randint(10,size=(9))
print(s)

m = np.reshape(s,(3,3))
print(m)

l = np.reshape(m,(9,1))
print(l)
 
m[(m<5)]=0
m[(m>=5)]=1
print(m)


[9 1 8 9 7 3 5 8 3]
[[9 1 8]
 [9 7 3]
 [5 8 3]]
[[9]
 [1]
 [8]
 [9]
 [7]
 [3]
 [5]
 [8]
 [3]]
[[1 0 1]
 [1 1 0]
 [1 1 0]]
